cryptonite_final_project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'cryptonite_final_project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^game/', include('notfirstapp.urls',namespace='game')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notfirstapp/urls.py
from django.conf.urls import patterns, url, include
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView
from notfirstapp import views

urlpatterns = patterns('',
	
	#login
	url(r'^login/',views.login_user, name="LoginPage"),
	url(r'^logout/$','django.contrib.auth.views.logout', {'next_page':'game:indexPage'},name="LogoutPage"),
	#signup
	url(r'^signup/',views.SignUpView.as_view(),name='SignUpPage'),

	#User
	url(r'^profile/(?P<pk>\d+)/$',views.ProfileView.as_view(),name='ProfilePage'),
	url(r'^profile/(?P<pk>\d+)/update/$',views.ProfileUpdateView.as_view(),name='ProfileUpdatePage'),

	#index page
	url(r'^$', views.IndexView.as_view(), name="indexPage"),
	# url(r'^(?P<game_id>\d+)/$', views.DetailPageController, name='DetailPage'),
	
	
	#manager part
	url(r'^manager/upload/$',login_required(views.GameCreateView.as_view()),name='GameFormPage'),
	url(r'^manager/deploy/$',login_required(views.GameDeployView.as_view()),name='GameDeployPage'),
	url(r'^manager/gamearchive/upload/$',login_required(views.GameUploadView.as_view()),name='GameArchiveUploadPage'),
	url(r'^manager/(?P<pk>\d+)/$',login_required(views.GameDetailView.as_view()),name='GameDetailPage'),
	url(r'^manager/$',login_required(views.GameListView.as_view()),name='GameManagePage'),
	url(r'^manager/(?P<pk>\d+)/rank/$',login_required(views.ScoreRankView.as_view()),name='ScoreRankPage'),
	url(r'^manager/simplelist/$',TemplateView.as_view(template_name='game.html'),name='SimpleGameListPage'),
	
	
	#image part
	url(r'^image/upload/$',login_required(views.ImageView.as_view()),name='ImageFormPage'),
	url(r'^image/(?P<pk>\d+)/$',views.ImageDetailView.as_view(),name='ImageDetailPage'),
	url(r'^image/$',views.ImageListView.as_view(),name='ImageListPage'),

	#Gallery part
	url(r'^gallery/$',views.GameGalleryView.as_view(),name='GameGalleryPage'),

	#PlayGame part
	url(r'^favorite/', views.favorite),
	url(r'^unfavorite/', views.unfavorite),	
	url(r'^playgame/(?P<game_slug>[a-zA-Z0-9_.-]+)$',views.GamePlayView.as_view(),name='GamePlayPage'),


	#Comment Part
	url(r'^comment/(?P<game_slug>[a-zA-Z0-9_.-]+)$',views.CommentListView.as_view(),name='CommentListPage'),
	url(r'^comment/create/$',views.CommentCreateView.as_view(),name='CommentCreatePage'),

	#api part ScoreRankApiView
	url(r'^rank/(?P<pk>\d+)/$',views.ScoreRankApiView,name='ScoreRankApi'),
	
	#Games html files.
	url(r'^2048/$',TemplateView.as_view(template_name='notfirstapp/2048.html'),name='GameDemoPage'),
	url(r'^asteroids/$',TemplateView.as_view(template_name='notfirstapp/asteroids.html'),name='Asteroids'),
	url(r'^snake/$',TemplateView.as_view(template_name='notfirstapp/snake.html'),name='Snake'),
	url(r'^starship/$',TemplateView.as_view(template_name='notfirstapp/starship.html'),name='Starship'),
	url(r'^alien/$',TemplateView.as_view(template_name='notfirstapp/alien.html'),name='Alien'),
    url(r'^filler/$',TemplateView.as_view(template_name='notfirstapp/fillerGame.html'),name='Filler Game'),
	url(r'^libgdx/$',TemplateView.as_view(template_name='notfirstapp/gamelibgdx.html'),name='libgdx'),
	
	#blog
	url(r'^blog/', 'notfirstapp.views.blogIndex', name='blog'),
	url(
    r'^blog/view/(?P<slug>[^\.]+).html', 
	'notfirstapp.views.view_post', 
    name='view_blog_post'),
	url(
    r'^blog/category/(?P<slug>[^\.]+).html', 
    'notfirstapp.views.view_category', 
    name='view_blog_category'),
	
	
)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT}))

		
		
		
		
		
		
		
		
		
		

notfirstapp/forms.py
from django import forms
from .models import *
from django.contrib.auth.models import User
from django.forms.widgets import *
from django.contrib.auth.forms import UserCreationForm

class GameForm(forms.ModelForm):
    class Meta:
    	model= Game
        exclude=['depolyed_path']

class GameCreateForm(forms.Form):
    gamename = forms.CharField(required=0)
    image = forms.ImageField(label='Select a image',
        help_text='max. 42 megabytes')

class ImageForm(forms.Form):
    imagefile = forms.ImageField(
        label='Select a image',
        help_text='max. 42 megabytes'
    )

class FigureForm(forms.ModelForm):
    class Meta:
        model=Figure
        fields=['name']

class PlayForm(forms.ModelForm):
    class Meta:
        model=Play
        exclude=[]

class ScoreRankForm(forms.ModelForm):
    # username=models.CharField(max_length=50)
    # playername=models.CharField(max_length=50)
    # gamename=models.CharField(max_length=50)
    class Meta:
        model=ScoreRank
        exclude=['rank']

class GameArchiveUploadForm(forms.ModelForm):

    class Meta:
        model=GameArchive
        widgets={
            'name': HiddenInput(),
            'fk_game': HiddenInput(),
        }
        exclude=[]
    # name = forms.CharField(max_length=50)
    # game = forms.FileField(label='Select a .zip file containing your game')

class UserCreateForm(UserCreationForm):
    """docstring for UserCreateForm"""
    firstname=forms.CharField(max_length=30,required=0)
    lastname=forms.CharField(max_length=30,required=0)
    email=forms.EmailField(max_length=50)

    def save(self, commit=True):
        # import pdb
        # pdb.set_trace()
        user=super(UserCreationForm,self).save(commit=True);
        user.set_password(self.cleaned_data["password1"])
        user.email=self.cleaned_data["email"]
        user.first_name=self.cleaned_data["firstname"]
        user.last_name=self.cleaned_data["lastname"]

        if commit:
            user.save()
        return user

class OnPlayUserForm(forms.ModelForm):
     """docstring for OnPlayUserForm"""
     class Meta:
        model=OnPlayUser
        # exclude=['user']
        widgets={
            'user':HiddenInput(),
        }
         

class CommentForm(forms.ModelForm):
    class Meta:
        model=GameComment
        exclude=[]
        widgets={
            'fk_game' : HiddenInput(),
            'fk_comment_poster': HiddenInput(),
            'comment': forms.Textarea(attrs={'rows': 2, 'cols': 240}),
        }

notfirstapp/views.py
from django.shortcuts import render,render_to_response,get_object_or_404,get_list_or_404
from django.views.decorators.http import require_http_methods
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt, csrf_protect
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import *
from django.template import RequestContext, loader
from django.views.generic import *
from django.views import generic
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied,SuspiciousOperation
from notfirstapp.models import *
from .forms import *
from .urls import *
from django.db.models import Avg
from django.db.models import Count
from django.db.models import Max
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import json
import pdb
# Create your views here.
class IndexView(ListView):
    # current_game=Game.objects.all()
    model = Game
    template_name = 'notfirstapp/index2.html'
    context_object_name = 'game_list'

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        game_list = Game.objects.order_by('-createTime')
        game_rate_list = []
        for game in game_list:
            ratings = GameRate.objects.filter(fk_game=game)
            game_rate_list.append((game, ratings.aggregate(Avg('rate')).values()[0]))

        spotlight_game_objects = SpotlightGame.objects.all()
        spotlight_games = []
        for spotlight_object in spotlight_game_objects:
            spotlight_games.append(spotlight_object.fk_game)

        spotlight_games_rate_list = []
        for game in spotlight_games:
            spotlight_ratings = GameRate.objects.filter(fk_game=game)
            spotlight_games_rate_list.append((game, spotlight_ratings.aggregate(Avg('rate')).values()[0]))

        top_games_list_one = game_list[0:4]
        top_games_list_two = game_list[4:8]

        context['spotlight_games_rate_list'] = spotlight_games_rate_list
        context['game_list'] = game_list
        context['top_games_list_one'] = top_games_list_one
        context['top_games_list_two'] = top_games_list_two
        context['game_rate_list'] = game_rate_list
        context['user'] = self.request.user
        return context



	# return HttpResponse(template.render(context))

class SignUpView(FormView):
    # form_class=UserCreationForm
    form_class=UserCreateForm
    template_name='notfirstapp/signup.html'

    def form_valid(self,form):
        user=form.save()
        OnPlayUser(user=user).save()
        return self.get_success_url();


    def form_invalid(self,form):
        # formWithError = AccountForm(data=form.data)

        return render(self.request,'notfirstapp/signup.html',{'form':form});

    def get_success_url(self):

        return HttpResponse(render(self.request,'notfirstapp/loginframe.html',{'alert':'SignUp Successd!'}))

    def get_fail_url(self):

        return render(self.request,'notfirstapp/signup.html',{'form':form});

class ProfileView(View):
    model=OnPlayUser
    template_name='notfirstapp/profile.html'


    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated():
            raise PermissionDenied("You have to login to see others' profile")
        user=OnPlayUser.objects.get(user__id=self.kwargs.get('pk'))
    	game=GameVisit.objects.filter(fk_visiter=self.kwargs.get('pk'))

    	game_list=Favorite.objects.filter(fk_visiter=self.kwargs.get('pk'))

    	gameplayed=game.count()

    	lastplayed= "none"
    	if gameplayed > 0:
    		lastplayed=game.latest('visit_time')


    	visit=GameVisit.objects.filter(fk_visiter=self.kwargs.get('pk')).extra({'visit_time' : "date(visit_time)"}).values('visit_time').annotate(play_count=Count('visit_time'))

        context={'player':user,  'last': lastplayed, 'gameplayed': gameplayed, 'visit': visit, 'favorite': game_list}
        if 'is_updated' in self.request.GET and self.request.GET.get('is_updated')==u'1':
            context['is_updated']='1'

        return render_to_response('notfirstapp/profile.html',context,context_instance=RequestContext(request))

    # def get(self, request, *args, **kwargs):
    #     raise PermissionDenied()

class ProfileUpdateView(UpdateView):
    model=OnPlayUser
    template_name="notfirstapp/profileupdate.html"
    form_class=OnPlayUserForm
    
    def get_success_url(self):
        return reverse('game:ProfilePage',kwargs={'pk':self.object.user.id})+"?is_updated=1"
        


class FigureFormView(CreateView):
	"""docstring for FigureFormView"""
	context_object_name='figureform.html'
	form_class=FigureForm

	def post(self, request, *args, **kwargs):
		form=self.form_class(request.POST)

                if form.is_valid():
                # newGame=Game(gamename=form.data[''])
                    return self.form_valid(form)
                else:
                    return self.form_invalid(form)

        def form_valid(self,form):
                self.object = form.save()
                # self.object=obj
                # self.object.save()
                self.id=self.object.id
                return HttpResponseRedirect(self.get_success_url())
	
    # def get_form(self, form_class):
    #     form = (super(GameCreateView, self)).get_form(form_class)
    #     current_account = Account.objects.all()
    #     form.fields['fk'].queryset = current_images 
    #     return form

        def get_success_url(self):
                return reverse('game:FigureDetailPage',kwargs={'pk': self.id})

class ScoreRankView(ListView):
    template_name='notfirstapp/ranklist.html'
    model=ScoreRank

    context_object_name='rank_list'

    # def post(self, request, *args, **kwargs):
    #     postdata=self.request.POST

    #     jsondata=json.load(postdata)
    #     data['Game_id']=get_object_or_404(Game,id=self.kwargs['pk'])
    #     data['Figure_id']=Figure_id(name=jsondata['figure'],User_id=get_object_or_404(User,username=jsondata['username']))
    #     date['score']=jsondata['score']
    #     form=ScoreRankForm(data)

    #     if form.is_valid():
    #     # newGame=Game(gamename=form.data[''])
    #         return self.form_valid(form)
    #     else:
    #         return self.form_invalid(form)


    def form_valid(self,form):
        form.save();

    def get_context_data(self, **kwargs):
        gameid=self.kwargs['pk']
        game=get_object_or_404(Game,pk=gameid)

        context=super(ScoreRankView,self).get_context_data(**kwargs)
        rank_list=ScoreRank.objects.filter(Game_id=gameid).order_by('-score')
        context['rank_list']=rank_list
        context['game']=game
        # context['user']=self.request.user
        return context

class GameGalleryView(ListView):
    # form_class=GameForm
    template_name = "notfirstapp/gamegallery.html"
    context_object_name = 'game_list'
    queryset=Game.objects.order_by('-createTime')

class GameListView(ListView):
	# form_class=GameForm
	template_name = "notfirstapp/gamelist.html"
	context_object_name = 'game_list'

	def get_queryset(self):
        	return Game.objects.filter(own__User_id=self.request.user).order_by('-createTime')

    

class GameCreateView(FormView):
    # Handle file upload
    template_name="notfirstapp/gameform.html"
    form_class=GameCreateForm

    def post(self, request, *args, **kwargs):
        form=self.form_class(request.POST,request.FILES)
        if form.is_valid():
        	# newGame=Game(gamename=form.data[''])
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self,form):
        img=Image(imagefile=form.cleaned_data['image'])
        img.save()
        game=Game(gamename=form.cleaned_data['gamename'],fk_image=img)
        game.save()
        ownership=Own(Game_id=game,User_id=self.request.user)
        ownership.save()
    	self.id=game.id
    	return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
    	return reverse('game:GameDetailPage',kwargs={'pk': self.id})

class GameDetailView(DetailView):
    model = Game
    template_name = 'notfirstapp/gamedetail.html'
    context_object_name = 'game'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(GameDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        game=context['game']
        context['appname'] = 'notfirstapp'
        context['back_url']=reverse('game:GameManagePage')
        context['available_archives']=GameArchive.objects.filter(fk_game=game)
        context['form']=GameArchiveUploadForm(initial={'name':game.gamename,'fk_game':game})
        return context


class ImageView(FormView):
    # Handle file upload
    template_name="notfirstapp/imageform.html"
    form_class=ImageForm

    def get_context_data(self, **kwargs):
    	context = super(ImageView, self).get_context_data(**kwargs)
    	context['uploaded']=Image.objects.all();
    	return context;

    def form_valid(self,form):
    	newImage=Image(
    		imagefile=self.get_form_kwargs().get('files')['imagefile'])	
    	newImage.save();
    	self.id=newImage.id

    	return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
    	return reverse('game:ImageFormPage')

class ImageDetailView(DetailView):
    model = Image
    template_name = 'notfirstapp/imagedetial.html'
    context_object_name = 'image'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(ImageDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['appname'] = 'notfirstapp'
        return context


class ImageListView(ListView):
    model = Image

notfirstapp/templates/notfirstapp/alien.html
{% load staticfiles%}
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Alien Invasion</title>
  <h1 align="center">Alien Invasion</h1>
  <link href={% static "notfirstapp/js/alien/base.css" %} rel="stylesheet" type="text/css" />

</head>
<body>
  <div id='container'>
    <canvas id='game' width='320' height='480'></canvas>
  </div>
  <script src={% static "notfirstapp/js/alien/engine.js" %}></script>
  <script src={% static "notfirstapp/js/alien/game.js" %}></script>
</body>
</html>

notfirstapp/templates/notfirstapp/base3.html
{% load staticfiles%}
<!DOCTYPE html>
<html>


  <head>
    <title>Game Hosting Site</title>
    

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Global variables -->
    <script  type="text/JavaScript">var STATIC_URL = "{{ STATIC_URL|escapejs }}"; var APP_NAME="notfirstapp/";</script>
    <!-- Jquery -->
    <script type="text/JavaScript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/JavaScript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css"/>
    <script type="text/JavaScript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

    <link href="{% static "notfirstapp/css/font-awesome.min.css"%}" rel="stylesheet"/>
    <link href="{% static "notfirstapp/css/templatemo_style.css"%}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static "notfirstapp/css/templatemo_misc.css"%}"/>

    <!-- <link href={% static "notfirstapp/css/circle.css"%} rel="stylesheet"> -->
    <link href="{% static "notfirstapp/css/jquery.bxslider.css"%}" rel="stylesheet"/>
    <link rel="stylesheet" href="{% static "notfirstapp/css/nivo-slider.css"%}"/>
    <link rel="stylesheet" href="{% static "notfirstapp/css/slimbox2.css"%}" type="text/css" media="screen"/>
    <!-- <link href='http://fonts.googleapis.com/css?family=Raleway:400,100,600' rel='stylesheet' type='text/css'> -->
    

    

    <script type="text/JavaScript" src="{% static "notfirstapp/js/slimbox2.js"%}"></script>

    <!-- ddsmoothmenu -->
    <link rel="stylesheet" type="text/css" href="{% static "notfirstapp/css/ddsmoothmenu.css"%}"/>
    <script type="text/javascript" src="{% static "notfirstapp/js/ddsmoothmenu.js"%}"></script>

    <script src="{% static "notfirstapp/js/jquery.nivo.slider.pack.js"%}"></script>
    <script src="{% static "notfirstapp/js/jquery.singlePageNav.js"%}"></script>
    
  </head>
  {%block head%}{%endblock head%}
  
  
  
  


<body>
  <style type="text/css" scoped >
    div.templatemo_top{
      border-bottom: 5px solid rgb(114,184,66);
    }
	
  </style>
  <div class=''>
    <div class=''>
      <header>
      <!-- start menu -->
        <div id="templatemo_home">
          <div class="templatemo_top container-fluid" style="height:auto">
            <div class="templatemo_container">
              <div class='row'>
                <div class="col-sm-3 col-md-3">
                  <div class="logo navbar-brand">
                    <a rel="nofollow" href= "{%url 'game:indexPage' %}" class="" >
                      <img src="{% static "notfirstapp/images/templatemo_logo.png"%}" alt="logo"/>
                    </a>
                  </div>
                </div>
                <div class="col-sm-9 col-md-9 templatemo_col9">
                  <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                    <span class="icon-bar" style='background:black'></span>
                    <span class="icon-bar" style='background:black'></span>
                    <span class="icon-bar" style='background:black'></span>
                  </button>

                  <div id="top-menu" class="collapse navbar-collapse navHeaderCollapse">
                    <nav class="mainMenu">
                      <ul class="nav navbar-nav navbar-right">
					  
                        {%if user.is_authenticated%}
                        <li><a class="menu"> Hi, {{user.username}}</a></li>
                        {%endif%}
						
                        {%block home%}
                        <li><a class="menu" href= "{% url 'game:indexPage' %}">Home</a></li>
                        {%endblock home%}
						
                        {%block about%}
                        <li><a class="menu" href= "#templatemo_about">About</a></li>
                        {%endblock about%}
						
                        {%block game%}
                        <li><a class="menu" href= "{% url 'game:GameGalleryPage' %}">Gallery</a></li>
                        {%endblock game%}

						
						
                        {%if user.is_authenticated%}
                          <li><a class="menu" href= "{% url 'game:GameManagePage' %}">MyGames</a></li>
                          <li><a class="menu" href= "{% url 'game:LogoutPage' %}">Logout</a></li>
                        {%else%}
                          <li><a class="menu" href= "{% url 'game:LoginPage' %}">Login</a></li>
                        {%endif%}
						
						
                      </ul>
                    </nav>
                  </div>
                </div>
              </div>
            </div>
            <div id='headerbar'></div>
          </div>
        </div>
        <div class="clear"></div>
      </header>
    </div>
  </div>


  {%block content%}{%endblock content%}



    

{%block endscript%}{%endblock endscript%}

{%block tail%}{%endblock tail%}
</body>
</html>
<!--
    Free Template by templatemo
    http://www.templatemo.com
-->

notfirstapp/templates/notfirstapp/gamedetail.html
{%extends "notfirstapp/base2.html"%}
{%load staticfiles%}
{%block content%}
	{% if game %}
	<div class='container-fluid'>
		<div class='row '>
			<div class='col-xs-2'></div>
			<div id="gameinfo" class=' col-xs-8 jumbotron' style='margin-top:12%;'>
				<table class='table table-hover' style='vertical-align:center;'>
					<thead>
						<tr>
							<th>Game Info</th>
						</tr>
						<tr>
							<th class='col-xs-1'>Game Icon</th>
							<th class='col-xs-3'>Game Name</th>
							<th class='col-xs-3'>Create Time</th>
						</tr>
					</thead>
					<tbody>
						<tr>
							<td class='col-xs-1'>
								<img id="gameposter" src="{{game.fk_image.imagefile.url}}" alt={{game.fk_image.imagefile.name}} style="max-width:80px;">
							</td>
							<td class='col-xs-3' >{{game.gamename}}</td>
							<td>{{game.createTime}}</td>
						</tr>
					</tbody>
				</table>
				<!-- archives list -->
				<table class='table table-hover'>
					<thead>
						<tr>
							<th>Available_Archives</th>
						</tr>
					</thead>
					<tbody>
						{% for archive in available_archives%}
							<tr>
								<td class='col-xs-6'>{{archive.gamefile}}</td>
								<td class='col-xs-2'>{{archive.upload_time}}</td>
							</tr>
						{%endfor%}
					</tbody>
				</table>

				<table class='table table-hover'>
					<tr>
						<th>Actions</th>
					</tr>
					<tr>
						<td class='col-xs-2'>
							<a href="#Upload_Form" id='Upload_Button'>Upload Game</a>
						</td>
						<td class='col-xs-2'>
							<a href="{{back_url}}">BACK</a>
						</td>
					</tr>
				</table>
				<form action="{% url 'game:GameArchiveUploadPage'%}" method="post" enctype="multipart/form-data" hidden='1' id='Upload_Form'>
					{% csrf_token %}
					<table class='table'>
						<thead>
							<th>Game Upload Form</th>
						</thead>
						<tbody>
							{{ form.as_table }}
							<tr>
								<td></td>
								<td></td>
								<td><input type="submit" value="submit" /></td>
							</tr>
						</tbody>
    				
					</table>
				</form>
			</div>
		</div>



			


		</div>
	
    {% else %}
		<p>Error. Cannot find the game.</p>
	{% endif %}
{%endblock content%}


{%block endscript%}
	<script type="text/javascript">
		$(document).ready(function(){
				$('a#Upload_Button').click(function(){
					$('form#Upload_Form').removeAttr('hidden');
			});
		});
	</script>
{%endblock endscript%}

{%block about%}{%endblock about%}

notfirstapp/templates/notfirstapp/loginpopup.html
		<div class='col-xs-offset-8'>
			<p style='text-align:left'>
				<a class='btn btn-primary' role='btn' href="{% url 'game:LoginPage'%}?next={{request.path}}">Login</a> {{message}}
			</p>
		</div>

		

notfirstapp/templates/notfirstapp/signup.html
{%extends 'notfirstapp/base2.html'%}
{%load staticfiles%}
{% load pdbDebug %}


{%if user.is_anonymous%}
	{%block head%}

		<!-- Basics -->
		
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		
		<title>Login</title>

		<!-- CSS -->
		
		<link rel="stylesheet" href={%static 'notfirstapp/css/reset.css'%}>
		<link rel="stylesheet" href={%static 'notfirstapp/css/animate.css'%}>
		<!-- <link rel="stylesheet" href={%static 'notfirstapp/css/styles.css'%}> -->
		
	{%endblock head%}

		<!-- Main HTML -->
		
	{%block content%}
		
		<!-- Begin Page Content -->
		<div class="container-fluid" id='signupForm'>

			
			<div class='row'>
				<div class='col-xs-6 col-xs-offset-3 jumbotron' style="margin-top:5%">
					<div class='row'>
						<div class='col-xs-10 col-xs-offset-1'>
							<h1 style="background:rgb(238, 238, 238); margin:0 auto 20px auto">Sign Up</h1>
						</div>
					</div>
					<div class='row'>
						<div class='col-xs-10 col-xs-offset-1'>
							{{ form.name_of_field.errors }}
							<form role="form" action='{%url "game:SignUpPage"%}' method='POST'>
								{% csrf_token %}
									<table class='table table-hover form-group'>
			        					{{ form.as_table }}
			 					   	</table>
			 					<p>
									<button id="Clear_Buttton"> Clear</button>
									<button type='submit'> Submit </button>
								</p>
							</form>
						</div>
					</div>
				</div>
				
			</div>	
			
			
		</div>
		
		
		<!-- End Page Content -->
	{%endblock content%}

	{%block tail%}
	{%endblock tail%}
	{%block endscript%}
	<script type="text/javascript">
		$(document).ready(function(){
			$('button#Clear_Buttton').click(function(){
				$('input').not(':button, :submit, :reset, :hidden').val('').removeAttr('checked').removeAttr('selected');
			});
		});
	</script>

	{%endblock endscript%}
{%else%}

{%endif%}

	
	
	
	
	
		
	